// Tressform — Supabase client (browser/anon + server/service-role), mock-mode aware.
//
// Per the "stub/mock everything" build decision: this module never throws
// just because env vars are missing. When NEXT_PUBLIC_SUPABASE_URL /
// NEXT_PUBLIC_SUPABASE_ANON_KEY are absent, `supabase` still gets a real
// supabase-js client pointed at a harmless local placeholder URL, and
// `SUPABASE_MOCK_MODE` is exported so callers (mainly lib/integrations/* and
// the app/api/* route handlers) know to short-circuit to fake data instead of
// making real network calls that would fail.
//
// Real wiring: set the three keys below in .env.local / Vercel project env
// (see .env.example), then run db/schema.sql against that project (e.g. via
// `mcp__Supabase__apply_migration` or the SQL editor).

import { createClient, type SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "./database.types";

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
const supabaseServiceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

export const SUPABASE_MOCK_MODE = !supabaseUrl || !supabaseAnonKey;

if (SUPABASE_MOCK_MODE && typeof window === "undefined") {
  // Server-side only, so this doesn't spam the browser console on every load.
  console.warn(
    "[Tressform] Supabase env vars are not set — running in MOCK MODE. " +
      "Auth, uploads, and all DB reads/writes will use in-memory fake data. " +
      "Set NEXT_PUBLIC_SUPABASE_URL / NEXT_PUBLIC_SUPABASE_ANON_KEY / " +
      "SUPABASE_SERVICE_ROLE_KEY to connect a real project."
  );
}

// A syntactically valid but non-routable URL so createClient() never throws
// when env vars are absent — nothing is ever actually sent to it because
// every call site checks SUPABASE_MOCK_MODE first.
const PLACEHOLDER_URL = "https://mock-project.supabase.co";
const PLACEHOLDER_KEY = "mock-anon-key";

// NOTE on typing: our Database type (lib/database.types.ts) is hand-written
// rather than generated by `mcp__Supabase__generate_typescript_types`, so it
// doesn't carry the `Relationships` field supabase-js's generic constraints
// expect — passing it as the client's generic makes every `.from(...)` query
// infer to `never`. Once a real project exists, regenerate database.types.ts
// with that tool and switch these back to `SupabaseClient<Database>` for full
// query type-safety. Until then, callers should annotate rows with the
// Row/Insert types from lib/database.types.ts by hand where useful.

/** Browser/user-scoped client — respects RLS, safe to import in client components. */
export const supabase: SupabaseClient<any> = createClient(
  supabaseUrl || PLACEHOLDER_URL,
  supabaseAnonKey || PLACEHOLDER_KEY,
  { auth: { persistSession: true, autoRefreshToken: true } }
);

/**
 * Service-role client — bypasses RLS. Server-only: import this ONLY from
 * app/api/* route handlers or other server code, never from a client
 * component. Falls back to the same mock-safe placeholder when unset.
 */
export function getSupabaseAdmin(): SupabaseClient<any> {
  return createClient(supabaseUrl || PLACEHOLDER_URL, supabaseServiceRoleKey || PLACEHOLDER_KEY, {
    auth: { persistSession: false, autoRefreshToken: false },
  });
}

export type { Database } from "./database.types";
export * from "./database.types";
